/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as appLayoutRouteImport } from './routes/(app)/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as appOnboardingRouteImport } from './routes/(app)/onboarding'
import { Route as appOrganizationsIndexRouteImport } from './routes/(app)/organizations/index'
import { Route as appFlowsIndexRouteImport } from './routes/(app)/flows/index'
import { Route as appOrganizationsCreateRouteImport } from './routes/(app)/organizations/create'
import { Route as appFlowsFlowidIndexRouteImport } from './routes/(app)/flows/$flowid/index'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authLayoutRoute,
} as any)
const appOnboardingRoute = appOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => appLayoutRoute,
} as any)
const appOrganizationsIndexRoute = appOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appFlowsIndexRoute = appFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appOrganizationsCreateRoute = appOrganizationsCreateRouteImport.update({
  id: '/organizations/create',
  path: '/organizations/create',
  getParentRoute: () => appLayoutRoute,
} as any)
const appFlowsFlowidIndexRoute = appFlowsFlowidIndexRouteImport.update({
  id: '/flows/$flowid/',
  path: '/flows/$flowid/',
  getParentRoute: () => appLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof appOnboardingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/flows': typeof appFlowsIndexRoute
  '/organizations': typeof appOrganizationsIndexRoute
  '/flows/$flowid': typeof appFlowsFlowidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof appOnboardingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/flows': typeof appFlowsIndexRoute
  '/organizations': typeof appOrganizationsIndexRoute
  '/flows/$flowid': typeof appFlowsFlowidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appLayoutRouteWithChildren
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(app)/onboarding': typeof appOnboardingRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(app)/organizations/create': typeof appOrganizationsCreateRoute
  '/(app)/flows/': typeof appFlowsIndexRoute
  '/(app)/organizations/': typeof appOrganizationsIndexRoute
  '/(app)/flows/$flowid/': typeof appFlowsFlowidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/organizations/create'
    | '/flows'
    | '/organizations'
    | '/flows/$flowid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/organizations/create'
    | '/flows'
    | '/organizations'
    | '/flows/$flowid'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/onboarding'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(app)/organizations/create'
    | '/(app)/flows/'
    | '/(app)/organizations/'
    | '/(app)/flows/$flowid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLayoutRoute: typeof appLayoutRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(app)/onboarding': {
      id: '/(app)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof appOnboardingRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/organizations/': {
      id: '/(app)/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof appOrganizationsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/flows/': {
      id: '/(app)/flows/'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof appFlowsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/organizations/create': {
      id: '/(app)/organizations/create'
      path: '/organizations/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof appOrganizationsCreateRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/flows/$flowid/': {
      id: '/(app)/flows/$flowid/'
      path: '/flows/$flowid'
      fullPath: '/flows/$flowid'
      preLoaderRoute: typeof appFlowsFlowidIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appOnboardingRoute: typeof appOnboardingRoute
  appOrganizationsCreateRoute: typeof appOrganizationsCreateRoute
  appFlowsIndexRoute: typeof appFlowsIndexRoute
  appOrganizationsIndexRoute: typeof appOrganizationsIndexRoute
  appFlowsFlowidIndexRoute: typeof appFlowsFlowidIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appOnboardingRoute: appOnboardingRoute,
  appOrganizationsCreateRoute: appOrganizationsCreateRoute,
  appFlowsIndexRoute: appFlowsIndexRoute,
  appOrganizationsIndexRoute: appOrganizationsIndexRoute,
  appFlowsFlowidIndexRoute: appFlowsFlowidIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface authLayoutRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLayoutRoute: appLayoutRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
