/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicLayoutRouteImport } from './routes/_public/layout';
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PublicRegisterRouteImport } from './routes/_public/register';
import { Route as PublicLoginRouteImport } from './routes/_public/login';
import { Route as ProtectedFlowsIndexRouteImport } from './routes/_protected/flows/index';
import { Route as ProtectedFlowsFlowidIndexRouteImport } from './routes/_protected/flows/$flowid/index';
const PublicLayoutRoute = PublicLayoutRouteImport.update({
    id: '/_public',
    getParentRoute: () => rootRouteImport,
});
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
    id: '/_protected',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const PublicRegisterRoute = PublicRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => PublicLayoutRoute,
});
const PublicLoginRoute = PublicLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PublicLayoutRoute,
});
const ProtectedFlowsIndexRoute = ProtectedFlowsIndexRouteImport.update({
    id: '/flows/',
    path: '/flows/',
    getParentRoute: () => ProtectedLayoutRoute,
});
const ProtectedFlowsFlowidIndexRoute = ProtectedFlowsFlowidIndexRouteImport.update({
    id: '/flows/$flowid/',
    path: '/flows/$flowid/',
    getParentRoute: () => ProtectedLayoutRoute,
});
const ProtectedLayoutRouteChildren = {
    ProtectedFlowsIndexRoute: ProtectedFlowsIndexRoute,
    ProtectedFlowsFlowidIndexRoute: ProtectedFlowsFlowidIndexRoute,
};
const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(ProtectedLayoutRouteChildren);
const PublicLayoutRouteChildren = {
    PublicLoginRoute: PublicLoginRoute,
    PublicRegisterRoute: PublicRegisterRoute,
};
const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(PublicLayoutRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
    PublicLayoutRoute: PublicLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
