packages:
  - apps/backend/*
  - apps/frontend/*
  - packages/*
  - tools/*

catalog:
  '@better-auth/stripe': ^1.4.4
  '@biomejs/biome': ^2.3.8
  '@storybook/react': ^8.5.0
  '@hono/node-server': ^1.19.6
  '@nx/js': ^22.1.3
  '@orpc/client': ^1.12.1
  '@orpc/contract': ^1.12.1
  '@orpc/openapi': ^1.12.1
  '@orpc/openapi-client': ^1.12.1
  '@orpc/server': ^1.12.1
  '@orpc/tanstack-query': ^1.12.1
  '@orpc/valibot': ^1.12.1
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-tooltip': ^1.2.8
  '@tabler/icons-react': ^3.35.0
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-form': ^1.26.0
  '@tanstack/react-query': ^5.90.11
  '@tanstack/react-router': ^1.139.12
  '@tanstack/react-router-devtools': ^1.139.12
  '@tanstack/router-plugin': ^1.139.12
  '@types/node': ^24.10.1
  '@types/pg': ^8.15.6
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  better-auth: ^1.4.4
  class-variance-authority: ^0.7.1
  dotenv-cli: ^11.0.0
  drizzle-kit: ^0.31.7
  drizzle-orm: ^0.44.7
  drizzle-valibot: ^0.4.2
  hono: ^4.10.7
  input-otp: 1.4.2
  lucide-react: ^0.555.0
  next-themes: ^0.4.6
  nx: ^22.1.3
  pg: ^8.16.3
  radix-ui: ^1.4.3
  react: ^19.2.0
  react-dom: ^19.2.0
  shx: ^0.4.0
  sonner: ^2.0.7
  stripe: ^20.0.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tailwindcss-animate: ^1.0.7
  tsdown: ^0.17.0-beta.4
  tsx: ^4.21.0
  typescript: ^5.9.3
  url-join: ^5.0.0
  valibot: ^1.2.0
  vite: ^7.2.6
  zod: ^4.1.13

ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'
