/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicUnauthorizedRouteImport } from './routes/_public/unauthorized'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedFlowsIndexRouteImport } from './routes/_protected/flows/index'
import { Route as ProtectedDocsIndexRouteImport } from './routes/_protected/docs/index'
import { Route as ProtectedDiagramsIndexRouteImport } from './routes/_protected/diagrams/index'
import { Route as ProtectedFlowsFlowidIndexRouteImport } from './routes/_protected/flows/$flowid/index'
import { Route as ProtectedDocsSlugIndexRouteImport } from './routes/_protected/docs/$slug/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicUnauthorizedRoute = PublicUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedFlowsIndexRoute = ProtectedFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedDocsIndexRoute = ProtectedDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedDiagramsIndexRoute = ProtectedDiagramsIndexRouteImport.update({
  id: '/diagrams/',
  path: '/diagrams/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedFlowsFlowidIndexRoute =
  ProtectedFlowsFlowidIndexRouteImport.update({
    id: '/flows/$flowid/',
    path: '/flows/$flowid/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedDocsSlugIndexRoute = ProtectedDocsSlugIndexRouteImport.update({
  id: '/docs/$slug/',
  path: '/docs/$slug/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/unauthorized': typeof PublicUnauthorizedRoute
  '/diagrams': typeof ProtectedDiagramsIndexRoute
  '/docs': typeof ProtectedDocsIndexRoute
  '/flows': typeof ProtectedFlowsIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/docs/$slug': typeof ProtectedDocsSlugIndexRoute
  '/flows/$flowid': typeof ProtectedFlowsFlowidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/unauthorized': typeof PublicUnauthorizedRoute
  '/diagrams': typeof ProtectedDiagramsIndexRoute
  '/docs': typeof ProtectedDocsIndexRoute
  '/flows': typeof ProtectedFlowsIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/docs/$slug': typeof ProtectedDocsSlugIndexRoute
  '/flows/$flowid': typeof ProtectedFlowsFlowidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/unauthorized': typeof PublicUnauthorizedRoute
  '/_protected/diagrams/': typeof ProtectedDiagramsIndexRoute
  '/_protected/docs/': typeof ProtectedDocsIndexRoute
  '/_protected/flows/': typeof ProtectedFlowsIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/docs/$slug/': typeof ProtectedDocsSlugIndexRoute
  '/_protected/flows/$flowid/': typeof ProtectedFlowsFlowidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/diagrams'
    | '/docs'
    | '/flows'
    | '/profile'
    | '/users'
    | '/docs/$slug'
    | '/flows/$flowid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/diagrams'
    | '/docs'
    | '/flows'
    | '/profile'
    | '/users'
    | '/docs/$slug'
    | '/flows/$flowid'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_public/unauthorized'
    | '/_protected/diagrams/'
    | '/_protected/docs/'
    | '/_protected/flows/'
    | '/_protected/profile/'
    | '/_protected/users/'
    | '/_protected/docs/$slug/'
    | '/_protected/flows/$flowid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/unauthorized': {
      id: '/_public/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof PublicUnauthorizedRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/flows/': {
      id: '/_protected/flows/'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof ProtectedFlowsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/docs/': {
      id: '/_protected/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ProtectedDocsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/diagrams/': {
      id: '/_protected/diagrams/'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof ProtectedDiagramsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/flows/$flowid/': {
      id: '/_protected/flows/$flowid/'
      path: '/flows/$flowid'
      fullPath: '/flows/$flowid'
      preLoaderRoute: typeof ProtectedFlowsFlowidIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/docs/$slug/': {
      id: '/_protected/docs/$slug/'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof ProtectedDocsSlugIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedDiagramsIndexRoute: typeof ProtectedDiagramsIndexRoute
  ProtectedDocsIndexRoute: typeof ProtectedDocsIndexRoute
  ProtectedFlowsIndexRoute: typeof ProtectedFlowsIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedDocsSlugIndexRoute: typeof ProtectedDocsSlugIndexRoute
  ProtectedFlowsFlowidIndexRoute: typeof ProtectedFlowsFlowidIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedDiagramsIndexRoute: ProtectedDiagramsIndexRoute,
  ProtectedDocsIndexRoute: ProtectedDocsIndexRoute,
  ProtectedFlowsIndexRoute: ProtectedFlowsIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedDocsSlugIndexRoute: ProtectedDocsSlugIndexRoute,
  ProtectedFlowsFlowidIndexRoute: ProtectedFlowsFlowidIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicUnauthorizedRoute: typeof PublicUnauthorizedRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicUnauthorizedRoute: PublicUnauthorizedRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
